# Generated by Django 5.0.4 on 2024-05-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads_images/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
