# Generated by Django 5.0.4 on 2024-05-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoHandler', '0002_uploadimage_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='title',
            field=models.CharField(default='Some text', max_length=100),
        ),
    ]
