# Generated by Django 5.0.4 on 2024-05-21 02:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoHandler', '0003_uploadimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='title',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='my_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(default='photoHandler/images/noimage.svg', upload_to='uploads_images/'),
        ),
    ]
