# Generated by Django 5.0.4 on 2024-05-23 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoHandler', '0004_remove_uploadimage_title_uploadimage_my_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='processed_images/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('my_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='uploads_images/'),
        ),
    ]
